---
apiVersion: v1
kind: Secret
metadata:
  name: smtp-credentials
type: Opaque
stringData:
  SMTP_USERNAME: bob@example.com
  SMTP_PASSWORD: not-really-a-password
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smtp-config
data:
  SMTP_SERVER: smtp.example.com
  SERVER_HOSTNAME: smtp.local
  SMTP_HEADER_TAG: relayed from homelab
