---
apiVersion: v1
kind: Service
metadata:
  name: email-smart-relay
spec:
  selector:
    app: email-smart-relay
  type: LoadBalancer
  ports:
  - port: 25
    targetPort: 2500
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: email-smart-relay
spec:
  selector:
    matchLabels:
      app: email-smart-relay
  serviceName: email-smart-relay
  replicas: 1
  template:
    metadata:
      labels:
        app: email-smart-relay
    spec:
      containers:
      - name: smtp
        image: docker.flame.org/library/email-smart-relay:latest
        envFrom:
          - configMapRef:
              name: smtp-config
          - secretRef:
              name: smtp-credentials
              optional: true
        ports:
        - containerPort: 2500
          name: smtp
        volumeMounts:
        - name: smtp-queue
          mountPath: /var/spool/postfix
  volumeClaimTemplates:
  - metadata:
      name: smtp-queue
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
